### ISSUE TITLE
GetService json unmarshall error

### ISSUE THREAD

**Issue by justinkelly** [docker/go-dockercloud#12]
Hi DockerCloud Go crew,

If I follow the GetService example in the docs 
https://docs.docker.com/apidocs/docker-cloud/?go#get-the-logs-of-a-service

```
import "github.com/docker/go-dockercloud/dockercloud"

service, err := dockercloud.GetService("7eaf7fff-882c-4f3d-9a8f-a22317ac00ce")

if err != nil {
  log.Println(err)
}

if err = service.Update(dockercloud.ServiceCreateRequest{Target_num_containers: 3}); err != nil {
   log.Println(err)
}
```
and replace the uuid with one of my service uuid I get teh following error when i run the code

```
json: cannot unmarshal number into Go value of type string
```

Any help with this would be greatly appreciated!!!!

cheers

justin

**Comment by MaximeHeckel** [comment]
Hi @justinkelly I'll take a look at it right now

**Comment by justinkelly** [comment]
Awesome, thanks!!

**Comment by MaximeHeckel** [comment]
The issue has been identified, it's not directly related to the SDK, I'll keep in touch once the fix is there

**Comment by justinkelly** [comment]
thanks @MaximeHeckel

**Comment by marcinwyszynski** [comment]
Hey it would be fantastic if you could please kindly consider resolving it.

**Comment by MaximeHeckel** [comment]
@marcinwyszynski It will be solved in the next release

**Comment by marcinwyszynski** [comment]
Great! Will log fetching be fixed, too?

**Comment by MaximeHeckel** [comment]
This is already fix with the up to date version

**Comment by marcinwyszynski** [comment]
Not with the one I just fetched today.

**Comment by MaximeHeckel** [comment]
@marcinwyszynski can you open another issue with your code?

**Comment by MaximeHeckel** [comment]
@justinkelly it should be fixed can you give a try?

**Comment by justinkelly** [comment]
@MaximeHeckel thanks - i'll test it later today and report back - thanks!!
