### ISSUE TITLE
Support provider options in NodeCreateRequest

### ISSUE THREAD

**Issue by nextrevision** [docker/go-dockercloud#24]
[Provider options](https://docs.docker.com/apidocs/docker-cloud/#provider-options) are present in the NodeCluster struct, but not in the NodeCreateRequest even though it is exposed in the API. After some playing around, adding a `Provider_options` field with the type `ProviderOption` does will cause the API to return "400 BAD REQUEST". By setting the NodeCreateRequest struct to require a pointer of a `ProviderOption` struct, the API allows the request to go through:

Using the ProviderOption struct and not setting it in the request:

```
type NodeCreateRequest struct {
  Disk             int             `json:"disk,omitempty"`
  Name             string          `json:"name,omitempty"`
  NodeType         string          `json:"node_type,omitempty"`
  Provider_options ProviderOption `json:"provider_options,omitempty"`
  Region           string          `json:"region,omitempty"`
  Target_num_nodes int             `json:"target_num_nodes,omitempty"`
  Tags             []NodeTag       `json:"tags,omitempty"`
}
```

Will result in a JSON payload with the VPC and IAM options as empty hashes:

```
{
    "name": "test",
    "node_type": "/api/infra/v1/nodetype/aws/t2.micro/",
    "provider_options": {
        "iam": {},
        "vpc": {}
    },
    "region": "/api/infra/v1/region/aws/us-east-1/"
}
```

Instead, using a pointer and not setting it in the request:

```
type NodeCreateRequest struct {
  Disk             int             `json:"disk,omitempty"`
  Name             string          `json:"name,omitempty"`
  NodeType         string          `json:"node_type,omitempty"`
  Provider_options *ProviderOption `json:"provider_options,omitempty"`
  Region           string          `json:"region,omitempty"`
  Target_num_nodes int             `json:"target_num_nodes,omitempty"`
  Tags             []NodeTag       `json:"tags,omitempty"`
}
```

Will result in the following, working request:

```
{
    "name": "foobar-test-terraform",
    "node_type": "/api/infra/v1/nodetype/aws/t2.micro/",
    "region": "/api/infra/v1/region/aws/us-east-1/"
}
```

**Comment by willrstern** [comment]
@nextrevision I was messing with that earlier with some frustration.

**Comment by nextrevision** [comment]
Yeah, nested structs and don't play well with "omitempty".
